import assert from 'node:assert/strict';
import {simulate} from './battle-engine.js';
const rule=(type,value,target='target')=>({event:'manual',condition:{type:'always'},target,action:{type,value},chance:100});
const move=(id,type='fuego',power=80,rules=[])=>({id,name:id,definition:{type,category:'physical',power,accuracy:100,criticalChance:0,priority:0,rules}});
const entity=(id,type='fuego',hp=100)=>({id,name:id,definition:{types:[type],hp,attack:100,defense:100,specialAttack:100,specialDefense:100,speed:100,moveIds:['a','b','c'],uniqueMoveId:'d',globalAbilityId:'none',uniqueAbilityId:'none2'}});
const catalog={entities:{a:entity('a'),b:entity('b','agua')},moves:{a:move('a'),b:move('b'),c:move('c'),d:move('d')},abilities:{none:{id:'none',definition:{rules:[]}},none2:{id:'none2',definition:{rules:[]}}},effects:{},weathers:{lluvia:{id:'lluvia',name:'Lluvia',definition:{duration:5,fieldEffects:[]}}}};
const opts={left:'a',right:'b',catalog,chart:{fuego:{agua:'inmune'}},turns:2};
const result=simulate(opts);
assert.equal(result.ok,true);assert.equal(result.right.hp,100,'immunity negates damage');
assert.ok(result.left.hp<100,'other side deals damage');
assert.deepEqual(simulate(opts),result,'seeded result reproducible');
catalog.moves.a=move('a','fuego',0,[rule('heal',10,'self')]);
const heal=simulate({...opts,chart:{},turns:1});
assert.equal(heal.ok,true);
const r=rule('damage',7);r.conditions=[{type:'has_type',value:'fuego'},{operator:'AND',type:'weather_is',value:'lluvia'}];
catalog.moves.a=move('a','fuego',80,[r]);
const rain=simulate({...opts,weather:'lluvia',turns:1,chart:{}});
const dry=simulate({...opts,weather:'',turns:1,chart:{}});
assert.ok(rain.right.hp<dry.right.hp,'AND condition applies only in rain');
console.log('PASS: immunity, damage, reproducibility, healing, combined conditions');
