import assert from 'node:assert/strict';
import {validateDefinition} from './catalog-validation.js';
const move={kind:'global',type:'viento',category:'physical',power:80,accuracy:100,criticalChance:10,priority:0,rules:[]};
assert.doesNotThrow(()=>validateDefinition('moves',move));
assert.throws(()=>validateDefinition('moves',{...move,kind:''}),/clase/);
assert.throws(()=>validateDefinition('moves',{...move,accuracy:null}),/precisión/);
const rule={event:'manual',condition:{type:'always',value:''},conditions:[],target:'target',action:{type:'damage',value:'10'},chance:100,duration:0,limit:0};
assert.doesNotThrow(()=>validateDefinition('moves',{...move,rules:[rule]}));
assert.throws(()=>validateDefinition('moves',{...move,rules:[{...rule,action:{type:'custom',value:'hack'}}]}),/no implementada/);
assert.throws(()=>validateDefinition('moves',{...move,rules:[{...rule,chance:null}]}),/probabilidad/);
assert.throws(()=>validateDefinition('moves',{...move,rules:[{...rule,event:'on_exit'}]}),/evento/);
assert.throws(()=>validateDefinition('weathers',{duration:3,rules:[rule]}),/todavía no ejecuta/);
assert.throws(()=>validateDefinition('moves',{...move,rules:[{...rule,conditions:[{type:'always',value:'',operator:'X',negate:false}]}]}),/operador/);
console.log('PASS: clase obligatoria, campos vacíos, reglas admitidas, acciones desconocidas, eventos y condiciones');
