import assert from 'node:assert/strict';
import {simulate} from './battle-engine.js';
import {validateDefinition} from './catalog-validation.js';
const ent=id=>({id,name:id,definition:{types:['fuego'],hp:100,attack:100,defense:100,specialAttack:100,specialDefense:100,speed:id==='A'?110:90,moveIds:['cd','b','c'],uniqueMoveId:'d',globalAbilityId:'g',uniqueAbilityId:'u'}});
const move=(id,cd=0)=>({id,name:id==='cd'?'Poder de prueba':id,definition:{kind:'global',type:'fuego',category:'status',power:0,accuracy:100,criticalChance:0,priority:0,cooldown:cd,rules:[]}});
const catalog={entities:{A:ent('A'),B:ent('B')},moves:{cd:move('cd',2),b:move('b'),c:move('c'),d:{...move('d'),definition:{...move('d').definition,kind:'unique'}}},abilities:{g:{definition:{rules:[]}},u:{definition:{rules:[]}}},effects:{},weathers:{},fields:{},scenarios:{}};
validateDefinition('moves',catalog.moves.cd.definition);
const r=simulate({left:'A',right:'B',catalog,turns:3,leftOrders:['cd','b','b'],rightMove:'b',randomSource:()=>0.1});
assert.ok(r.log.includes('A tiene 2 turnos restantes para poder volver a usar Poder de prueba.'));
assert.ok(r.log.includes('A tiene 1 turno restante para poder volver a usar Poder de prueba.'));
assert.ok(r.log.includes('A puede volver a usar Poder de prueba.'));
assert.equal(r.left.cooldowns.cd,0);
console.log('PASS: cooldown 2 → 1 → disponible');
