import assert from 'node:assert/strict';
import {simulate} from './battle-engine.js';
const move=(id,cd)=>({id,name:id,definition:{kind:'global',type:'fuego',category:'physical',power:10,accuracy:100,criticalChance:0,priority:0,cooldown:cd,rules:[]}});
const moves={a:move('a',1),b:move('b',0),c:move('c',0),u:{...move('u',0),definition:{...move('u',0).definition,kind:'unique'}}};
const ability=id=>({id,name:id,definition:{kind:id==='ua'?'unique':'global',rules:[]}});
const ent=(id)=>({id,name:id,definition:{types:['fuego'],hp:200,attack:10,defense:200,specialAttack:10,specialDefense:200,speed:100,moveIds:['a','b','c'],uniqueMoveId:'u',globalAbilityId:'ga',uniqueAbilityId:'ua'}});
const catalog={entities:{x:ent('x'),y:ent('y')},moves,abilities:{ga:ability('ga'),ua:ability('ua')},effects:{},statuses:{},weathers:{},fields:{},scenarios:{}};
const chart={fuego:{fuego:'neutral'}};
const r1=simulate({left:'x',right:'y',chart,catalog,turns:1,leftOrders:[{move:'a'}],rightOrders:[{move:'b'}],randomSource:()=>.9});
assert.equal(r1.left.cooldowns.a,1,'el turno de uso no reduce cooldown');
const r2=simulate({left:'x',right:'y',chart,catalog,turns:2,leftOrders:[{move:'a'},{move:'b'}],rightOrders:[{move:'b'},{move:'b'}],randomTape:r1.randomTape,randomSource:()=>.9});
assert.equal(r2.left.cooldowns.a,0,'al final del turno siguiente baja a cero');
assert.ok(r2.log.some(x=>x.includes('puede volver a usar a')));
console.log('cooldown semantics ok');
