import assert from 'node:assert/strict';
import {simulate} from './battle-engine.js';
import {validateDefinition} from './catalog-validation.js';
const e=(id,type)=>({id,name:id,definition:{types:[type],hp:100,attack:100,defense:100,specialAttack:100,specialDefense:100,speed:100,moveIds:['a','b','c'],uniqueMoveId:'d',globalAbilityId:'g',uniqueAbilityId:'u'}});
const m=(id,rules=[])=>({id,name:id,definition:{type:'fuego',category:'status',power:0,accuracy:100,criticalChance:0,priority:0,rules}});
const rule=(type,value,target='self')=>({event:'manual',condition:{type:'always'},conditions:[],target,action:{type,value},chance:100,duration:0,limit:0});
const env=(id,fieldEffects)=>({id,name:id,definition:{duration:5,rules:[],fieldEffects}});
const fx=(type,filter,types,value,extra={})=>({type,filter,types,value,chance:100,timing:type==='damage_percent'||type==='heal_percent'?'round_end':'continuous',...extra});
const catalog={entities:{a:e('a','espectro'),b:e('b','agua')},moves:{a:m('a',[rule('set_scenario','inframundo')]),b:m('b'),c:m('c'),d:m('d')},abilities:{g:{definition:{rules:[]}},u:{definition:{rules:[]}}},effects:{},weathers:{},fields:{},scenarios:{inframundo:env('inframundo',[fx('damage_percent','exclude',['espectro','fuego'],5),fx('heal_percent','include',['espectro','fuego'],5)])}};
validateDefinition('scenarios',catalog.scenarios.inframundo.definition);
const result=simulate({left:'a',right:'b',catalog,turns:3,leftMove:'a',rightMove:'b'});
assert.ok(result.log.some(x=>x.includes('Se activa scenario')),'escenario activado por movimiento');
assert.equal(result.right.hp,85,'5 % daño a agua durante tres rondas');
assert.equal(result.left.hp,100,'espectro excluido del daño y curado hasta PS máximos');
assert.equal(result.scenario,'inframundo');
const five=simulate({left:'a',right:'b',catalog,turns:6,leftOrders:[{move:'a'},{move:'b'},{move:'b'},{move:'b'},{move:'b'},{move:'b'},{move:'b'}],rightMove:'b'});

assert.equal(five.scenario,'','el escenario expira tras 5 rondas');
assert.equal(five.right.hp,75,'solo cinco ticks de daño');
const power=env('coliseo',[fx('stat_change','all',[],2,{stat:'attack'}),fx('stat_change','all',[],-2,{stat:'specialAttack'}),fx('stat_change','all',[],3,{stat:'criticalChance'})]);
validateDefinition('scenarios',power.definition);
assert.throws(()=>validateDefinition('scenarios',{...power.definition,fieldEffects:[fx('stat_change','all',[],1,{stat:'hp'})]}),/estadística/);
const withPower=structuredClone(catalog);withPower.scenarios.coliseo=power;withPower.moves.a=m('a',[rule('set_scenario','coliseo')]);
const stages=simulate({left:'a',right:'b',catalog:withPower,turns:3,leftMove:'a',rightMove:'b'});
assert.equal(stages.left.stages.attack||0,0,'los modificadores ambientales no se acumulan en niveles permanentes');
assert.throws(()=>validateDefinition('scenarios',{...power.definition,fieldEffects:[fx('damage_percent','include',[],5)]}),/al menos un tipo/);
const block=env('purificador',[fx('block_status','all',[],undefined,{timing:'continuous'})]);
validateDefinition('fields',block.definition);
const withStatus=structuredClone(catalog);withStatus.fields.purificador=block;
withStatus.moves.a=m('a',[rule('set_field','purificador')]);withStatus.moves.b=m('b',[rule('apply_status','quemado','target')]);
const blocked=simulate({left:'a',right:'b',catalog:withStatus,turns:2,leftOrders:['a','b'],rightOrders:['b','b']});
assert.equal(blocked.left.status,null,'campo bloquea estado en activo');
const prevent=structuredClone(catalog);prevent.abilities.g={definition:{rules:[{...rule('prevent_environment','scenarios'),event:'on_enter',target:'self'}]}};
const stopped=simulate({left:'a',right:'b',catalog:prevent,turns:2,leftMove:'a',rightMove:'b'});
assert.equal(stopped.scenario,'','una habilidad puede impedir activar escenarios');
console.log('PASS: escenario activado por movimiento, duración 5, filtros por tipo, daño/curación %, estadística sin PS, bloqueo de estados');
