import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('./public/index.html',import.meta.url),'utf8');
for(const token of ['anim-physical','anim-special','anim-hit','anim-status','physicalRight','physicalLeft','specialPulse','hitShake','statusOrbit'])assert.match(html,new RegExp(token));
assert.match(html,/grid-template-columns:1fr 1fr!important/);
assert.match(html,/Efectos jugador/);assert.match(html,/Efectos rival/);assert.match(html,/Campo · Clima · Escenario/);assert.match(html,/Battle log/);
assert.match(html,/>Normal<\/button>/);assert.match(html,/>Rápida<\/button>/);assert.match(html,/>×2<\/button>/);
assert.match(html,/battleCancelMove/);assert.match(html,/>Cancelar<\/button>/);assert.match(html,/battleMoveInfo/);assert.match(html,/>Info<\/button>/);
assert.match(html,/setTimeout\(\(\)=>\{[\s\S]*?\},900\)/);
for(const ms of [650,250,800,350,1350,1650,900])assert.match(html,new RegExp(`wait\\(${ms}\\)`));
assert.match(html,/wait\(cat==='status'\?1300:1150\)/);
assert.match(html,/statusEffectText/);assert.match(html,/statBreakdown/);assert.match(html,/environmentEffectText/);assert.match(html,/logBody/);
assert.match(html,/battle-hp-fill/);assert.match(html,/transition:width 1\.15s linear/);
assert.match(html,/refreshOpenEffectsModal/);assert.match(html,/applyVisualEvent/);
const worker=fs.readFileSync(new URL('./worker.js',import.meta.url),'utf8');
assert.match(worker,/data\.type==="select_order"/);
assert.match(worker,/data\.type==="cancel_selection"/);
assert.match(worker,/type:"battle_selection"/);
assert.match(worker,/selection:\{host:null,guest:null\}/);
assert.match(html,/type:'select_order'/);
assert.match(html,/type:'cancel_selection'/);
assert.match(html,/m\.type==='battle_selection'/);
assert.ok(fs.existsSync(new URL('./.github/workflows/deploy-test.yml',import.meta.url)),'main debe conservar Deploy Universal Duels Test visible en Actions');
console.log('lab UI parity tests ok');
