import {simulate} from './battle-engine.js';
const move={id:'golpe',name:'Golpe',definition:{type:'fuego',category:'status',power:0,accuracy:100,criticalChance:0,priority:0,cooldown:0,rules:[{event:'manual',condition:{type:'always'},target:'self',chance:100,action:{type:'stat_change',stat:'speed',value:1}}]}};
const ab={id:'nada',name:'Nada',definition:{rules:[]}};
const ent=id=>({id,name:id,definition:{types:['fuego'],hp:100,attack:100,defense:100,specialAttack:100,specialDefense:100,speed:100,moveIds:['golpe','golpe2','golpe3'],uniqueMoveId:'golpe4',globalAbilityId:'nada',uniqueAbilityId:'nada2'}});
const moves={golpe:move,golpe2:{...move,id:'golpe2'},golpe3:{...move,id:'golpe3'},golpe4:{...move,id:'golpe4'}};
const abilities={nada:ab,nada2:{...ab,id:'nada2'}};
const catalog={entities:{a:ent('a'),b:ent('b')},moves,abilities,effects:{},statuses:{},weathers:{},fields:{},scenarios:{}};
const out=simulate({left:'a',right:'b',catalog,chart:{},turns:1,leftOrders:[{move:'golpe'}],rightOrders:[{move:'golpe2'}],randomSource:()=>0.1});
if(!Array.isArray(out.left.statSources)||!out.left.statSources.length) throw Error('statSources no registrado');
console.log('runtime shape regression ok');
