name = "duelo-pixel-rooms"
main = "worker.js"
compatibility_date = "2026-09-29"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[kv_namespaces]]
binding = "EDITOR_DRAFTS"
id = "1173494a63814d1b9093b9a409cf2832"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*", "/health", "/editor-api/*"]

[vars]
ACCESS_TEAM_DOMAIN = "nameless-water-b29a.cloudflareaccess.com"
ACCESS_AUD = "c38edfabcf3221f1ad4fa4c1b9d69e99600c921b83e99fc197c083afd9fa205c"
